import { createFileRoute } from "@tanstack/react-router";
import { useState, type ReactNode } from "react";
import { CheckCircle2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { PageIntro } from "@/components/page-shell";

export const Route = createFileRoute("/rejoindre")({ head: () => ({ meta: [{ title: "Rejoindre le réseau FORMA" }, { name: "description", content: "Formulaire d’adhésion pour prestataires qualifiés souhaitant rejoindre le réseau de coordination FORMA." }, { property: "og:title", content: "Rejoindre le réseau FORMA" }, { property: "og:description", content: "Prestataires qualifiés : présentez votre activité pour intégrer le réseau FORMA." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/rejoindre" }] }), component: Join });
function Join(){const [sent,setSent]=useState(false);return <><PageIntro eyebrow="Prestataires partenaires" title="Rejoindre le réseau FORMA." text="Électriciens, techniciens clim, nettoyage, traiteurs, photographes et autres métiers qualifiés peuvent présenter leur activité pour sélection."/><section className="py-20"><div className="section-shell grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Processus transparent</p><div className="mt-8 grid gap-4 text-sm leading-6 text-muted-foreground">{["Présentation de l’activité et des références disponibles.","Vérification des compétences, disponibilités et zones d’intervention.","Validation des conditions de collaboration.","Suivi qualité après chaque mission coordonnée par FORMA."].map(x=><p key={x} className="flex gap-3"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-accent"/>{x}</p>)}</div></div><form onSubmit={(e)=>{e.preventDefault();setSent(true)}} className="border border-border bg-card p-6 md:p-8"><div className="grid gap-5 sm:grid-cols-2"><Field label="Nom / Responsable"><Input required maxLength={100}/></Field><Field label="Métier / spécialité"><Input required maxLength={120}/></Field><Field label="Téléphone"><Input required type="tel" maxLength={18}/></Field><Field label="Zone d’intervention"><Input required maxLength={120}/></Field></div><Field label="Expérience et références"><Textarea required maxLength={1200} className="mt-6 min-h-36"/></Field><Button className="mt-6 h-11 w-full" type="submit">Soumettre ma candidature</Button>{sent&&<p className="mt-4 text-sm font-semibold text-accent">Candidature préparée. FORMA vous contactera pour les vérifications.</p>}</form></div></section></>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block text-xs font-bold uppercase text-muted-foreground">{label}<div className="mt-2">{children}</div></label>}