/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as FacilityRouteImport } from './routes/facility'
import { Route as FormationsRouteImport } from './routes/formations'
import { Route as SecuriteRouteImport } from './routes/securite'
import { Route as SolutionsRouteImport } from './routes/solutions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityRoute = FacilityRouteImport.update({
  id: '/facility',
  path: '/facility',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsRoute = FormationsRouteImport.update({
  id: '/formations',
  path: '/formations',
  getParentRoute: () => rootRouteImport,
} as any)
const SecuriteRoute = SecuriteRouteImport.update({
  id: '/securite',
  path: '/securite',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/evenements': typeof EvenementsRoute
  '/facility': typeof FacilityRoute
  '/formations': typeof FormationsRoute
  '/securite': typeof SecuriteRoute
  '/solutions': typeof SolutionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/evenements': typeof EvenementsRoute
  '/facility': typeof FacilityRoute
  '/formations': typeof FormationsRoute
  '/securite': typeof SecuriteRoute
  '/solutions': typeof SolutionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/evenements': typeof EvenementsRoute
  '/facility': typeof FacilityRoute
  '/formations': typeof FormationsRoute
  '/securite': typeof SecuriteRoute
  '/solutions': typeof SolutionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/evenements'
    | '/facility'
    | '/formations'
    | '/securite'
    | '/solutions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/evenements'
    | '/facility'
    | '/formations'
    | '/securite'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/evenements'
    | '/facility'
    | '/formations'
    | '/securite'
    | '/solutions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  EvenementsRoute: typeof EvenementsRoute
  FacilityRoute: typeof FacilityRoute
  FormationsRoute: typeof FormationsRoute
  SecuriteRoute: typeof SecuriteRoute
  SolutionsRoute: typeof SolutionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility': {
      id: '/facility'
      path: '/facility'
      fullPath: '/facility'
      preLoaderRoute: typeof FacilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations': {
      id: '/formations'
      path: '/formations'
      fullPath: '/formations'
      preLoaderRoute: typeof FormationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/securite': {
      id: '/securite'
      path: '/securite'
      fullPath: '/securite'
      preLoaderRoute: typeof SecuriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  EvenementsRoute: EvenementsRoute,
  FacilityRoute: FacilityRoute,
  FormationsRoute: FormationsRoute,
  SecuriteRoute: SecuriteRoute,
  SolutionsRoute: SolutionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
